spring.application.name=api-gateway
server.port=9000
spring.main.web-application-type=servlet
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

gateway.jwt.secret=Ms2+3M3mvlMz5TNpd5lzvkwpnY0PPQH/tr8wz0qByTo=


spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=loan-type-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://loan-type-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/loan-types/**

spring.cloud.gateway.server.webmvc.routes[2].id=loan-application-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://loan-application-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/loan-applications/**

spring.cloud.gateway.server.webmvc.routes[3].id=loan-officer-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://loan-officer-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/loan-officer/**

spring.cloud.gateway.server.webmvc.routes[4].id=customer-login
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/customers/login
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=SetPath=/api/v1/auth/customers/login

spring.cloud.gateway.server.webmvc.routes[5].id=customer-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://customer-service
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/customers/**

spring.cloud.gateway.server.webmvc.routes[6].id=credit-score
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://credit-score
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/credit-scores/**
