spring.application.name=credit-score
server.port=8000
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/freepdb1
spring.datasource.username=system
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.security.user.name=system
spring.security.user.password=root